### ISSUE TITLE
Remove dataType which is not defined in OWL

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF-Schema#25]
The dataType xs:duration is not defined in OWL. As any tranformation is difficult and the dataType is not of great importance, it is removed from SpecIF.

Reference: Hitzler, Krötzsch, Rudolph: "Foundations of Semantic Web Technologies", p. 117.

**Comment by oalt** [comment]
Hi Oskar!
You are wrong. The data type is very important. KARL MAYER transfers machine data using SpecIF in practice every day. We strongly need a duration for example for machine runtime, remaining times etc. So removing this data type will be a breaking change for SpecIF usage in use cases dealing with production data and also other behavioral data.
Regards
Oliver

**Comment by odungern** [comment]
.. fine, good to hear, Oliver. Didn't know xs:duration is actually used in practice. Keeping it means any property of this type becomes a string in RDF/OWL ... better than using a string in both worlds ;-)

**Comment by odungern** [comment]
Idea dismissed.
